DARPA-ASKEM/data-service

tds/routers/projects.py, tds/schema/project.py
To get assets you need to hit /projects/{id}
=> Removed assets from /projects endpoint

tds/routers/concepts.py
Implements functionality described in #71
=> Add facet search

tds/lib/errors.py, tds/routers/concepts.py
NOTE: since display names aren't cache, lookups are done on run. SLOWDOWN
=> Reformat facet

tds/routers/projects.py, tds/schema/resource.py
=> Assets returned as full objects.

scripts/upload_demo_data.py
Data files not generated yet. Will rebase after Powells stuff is in.
=> add concepts to datasets generated by simulation run

.github/workflows/build_sql.yaml
This fix prevents the issue we saw where the auto checks were not getting run properly.
=> Update to use automation user to push up commits

.github/workflows/build_sql.yaml, Makefile
Should only rebuild and reupload if the .sql files are recreated based on the makefile rules.
=> Refactor to try to force better conditional reloading of db

tds/routers/concepts.py
Fixes/corrects facet datasearch.
=> Fix facet search

askem.dbml, tds/autogen/info.json, tds/autogen/orm.py, tds/autogen/schema.py, tds/routers/models.py, tds/settings.py
Wanted to match the [recommended naming conventions](https://neo4j.com/docs/cypher-manual/current/syntax/naming/#_recommendations) to possibly make GPT-3 more accurate.
=> Fix enum names for provenance types

tds/routers/projects.py
=> Make asset type param optional

docker/scripts/populate-cache.cypher
Fixed upload script of concept nodes so all connections are accounted for
=> fixed script

tds/modules/model/controller.py, tds/modules/model/utils.py
@toddroper some minor tweaks to get the list model descriptions and `GET` on model parameters to work. Note the comment I added about `model_schema` vs `schema`.
=> Fix params and list models

tds/db/elasticsearch.py, tds/main.py, tds/settings.py
In settings, the values automatically get overwritten by whats in the env. The value of the setting should be the default.
=> Wait for ES to be healthy, then add indexes

tds/lib/utils.py, tds/modules/dataset/controller.py, tds/modules/dataset/model.py
- Cleaned up responses and unified list response.
- Added username to Dataset model.
=> Dataset Updates

tds/lib/utils.py
Tested and confirmed that modifying the patchable class does not modify the base class.
=> Fix patchable so it works as expected

tds/modules/dataset/model.py
Fixing groundings to match what was found in extractions.
=> Fix dataset groundings

migrate/seeds/es/indexes.json, tds/modules/model_configuration/model.py, tds/modules/model_configuration/response.py
- Added `amr_configuration` field to model configuration.
- Updated workflow index to disable dynamic mappings.
=> R.C. 0.4.3

migrate/seeds/es/indexes.json, migrate/seeds/es/model/biomd0000000249-model.json, migrate/seeds/es/model/biomd0000000294-model.json, migrate/seeds/es/model/biomd0000000955-model.json, migrate/seeds/es/model/biomd0000000960-model.json, migrate/seeds/es/model/biomd0000000983-model.json, migrate/seeds/es/model/sir_model.json, tds/db/base.py, tds/modules/model/controller.py, tds/modules/model_configuration/controller.py, tds/routers/projects.py, tds/schema/resource.py
- Updated model seeds with new format from @bgyori.
- Added timestamp ES mapping to enable date sorting on indexes.
- Updated TDS Model to format date before save.
- Updated `model_id` field to be keyword type to prevent ES analyzation.
- Fixed bug with artifacts not listed in project assets.
=> R.C. 0.5.4

Makefile, migrate/versions/d6ec58f4fd9a_add_publication_metadata.py, tds/autogen/orm.py, tds/autogen/schema.py
- Added `publication_data` field to `publication` table to store arbitrary metadata.
=> R.C. 0.5.5

tds/modules/simulation/model.py
This allows for Interventions to be included in a simulation payload
=> Add intervetions

tds/lib/datasets.py, tds/lib/s3.py, tds/modules/simulation/controller.py
- Added copy object function to s3 lib.
- Added endpoint to simulation controller to copy result files to dataset.
- Added function to dataset lib to copy sim object into dataset.
=> Feature: Copy Sim Results to Dataset

graph_relations.json, tds/db/graph/search_provenance.py, tds/modules/code/controller.py, tds/modules/code/model.py, tds/modules/provenance/controller.py, tds/schema/provenance.py
=> Update provenance to support models from code (not artifacts)

api.env.sample, migrate/seeds/es/indexes.json, tds/modules/document/__init__.py, tds/modules/document/controller.py, tds/modules/document/model.py, tds/modules/document/response.py, tds/settings.py
=> Add documents endpoint for publications/artifacts

tds/modules/dataset/model.py
Simple fix to make a passable example for `datasets`.
=> Fix dataset example

tds/modules/model/model.py
Recursively search for groundings instead of only looking in hard-coded place(s).
=> Refactor model grounding extraction

docker/Dockerfile, tds/server/build.py
completes https://github.com/DARPA-ASKEM/simulation-integration/issues/13#issuecomment-1755483569
=> Add healthcheck endpoint
